In [172]:
import numpy as np
import pandas as pd
import json

In [173]:
# file_name = "training.json"
# file_output = "training_stats.csv"
# data_name = "training"

In [174]:
file_name = "dev.json"
file_output = "dev_stats.csv"
data_name = "dev"

In [175]:
# file_name = "test.json"
# file_output = "test_stats.csv"
# data_name = "test"

In [176]:
f = open(file_name)
data = json.load(f)
f.close()

In [177]:
arr = data['data']
N = len(arr)

In [178]:
final_dict = {}

#### NUmber of texts

In [179]:
text_set = set()
for element in arr:
    text_set.add(element["context"])

n_texts = len(text_set)
final_dict["# of texts"] = n_texts
n_texts

64

#### Count Questions

In [180]:
n_questions = len(arr)
final_dict["# of MCQs"] = n_questions
n_questions

126

#### One answer per choice

In [181]:
n_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_ans = 0  
    for choice in choices:
        if choice["type"] == "Correct answer":
            n_ans +=1
    n_answers[idx] = n_ans

In [182]:
n_answers

array([1., 1., 1., 2., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       2., 1., 1., 1., 1., 1., 1.])

In [183]:
# for element in n_answers:
#     assert element == 1

#### Number of distractors

In [184]:
n_distractors = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_dist = 0 
    for choice in choices:
        if choice["type"] == "Distractor":
            n_dist +=1
    # assert n_dist < 5
    n_distractors[idx] = n_dist

In [185]:
n_distractors

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 4., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 2., 3., 2., 3., 2.,
       4., 3., 2., 3., 3., 3., 3.])

In [186]:
n_dist_mean = np.mean(n_distractors)
n_dist_std = np.std(n_distractors)

In [187]:
print(n_dist_mean)
print(n_dist_std)
final_dict["# of D"] = f"{n_dist_mean:0.2f} +- {n_dist_std:0.2f}"
final_dict["# of D"]

2.126984126984127
0.3776310239165181


'2.13 +- 0.38'

### Length of texts

In [188]:
def count_words(_string):
    arr = _string.split(" ")
    return len(arr)

In [189]:
len_texts = np.zeros(N)
for idx, element in enumerate(arr):
    context = element["context"]
    len_texts[idx] = count_words(context)

len_texts

array([ 298.,  336.,  265.,  295.,  295.,  320.,  258.,  298.,  343.,
        193.,  280.,  273.,  315.,  338.,  403.,  403.,  373.,  246.,
        246.,  247.,  247.,  270.,  262.,  262.,  262.,  262.,  262.,
        235.,  299.,  477.,  477.,  477.,  287.,  287.,  287.,  271.,
        271.,  213.,  288.,  288.,  288.,  288.,  231.,  293.,  290.,
        583.,  583.,  311.,  311.,  270.,  271.,  271.,  271.,  271.,
        277.,  369.,  222.,  325.,  290.,  296.,  296.,  296.,  296.,
        274.,  299.,  278.,  249.,  240.,  300.,  300.,  300.,  300.,
        279.,  279.,  306.,  293.,  277.,  246.,  231.,  231.,  248.,
        248.,  248.,  208.,  239.,  239.,  239.,  326.,  202.,  213.,
        259.,  259.,  337.,  337.,  303.,  583.,  583.,  265.,  265.,
        262.,  262.,  366.,  366.,  366.,  333.,  333.,  333.,  333.,
        343.,  343.,  428.,  428.,  428.,  428.,  428.,  428.,  407.,
        407.,  221.,  221., 2140.,  686., 1146., 1146., 1146., 1146.])

In [190]:
max_length_text = np.max(len_texts)
max_length_text

2140.0

In [191]:
text_mean = np.mean(len_texts)
text_std = np.std(len_texts)
print(text_mean)
print(text_std)

352.1031746031746
232.41277009710035


In [192]:
final_dict["Len(Text)"] = f"{text_mean:0.2f} +- {text_std:0.2f}"
final_dict["Max(Text)"] = max_length_text
final_dict["Len(Text)"]

'352.10 +- 232.41'

#### Length of answers

In [193]:
len_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "Correct answer":
            ans = choice["text"]
            len_answers[idx] = count_words(ans)

len_answers

array([ 2.,  7.,  1.,  9.,  1., 14.,  7.,  2.,  4.,  2.,  9.,  9.,  4.,
        1.,  8., 15.,  1.,  1.,  1.,  3.,  2.,  5.,  8.,  1.,  1.,  3.,
        3., 12.,  1.,  7.,  8., 14.,  3., 10.,  1.,  3.,  4.,  2.,  5.,
        1.,  1.,  2.,  8.,  2.,  6.,  3.,  2.,  1.,  3.,  5.,  1.,  1.,
        8.,  1., 13.,  6.,  7.,  1.,  1., 10.,  1.,  8.,  4.,  2.,  5.,
        3.,  3.,  6.,  2.,  1.,  9.,  4., 19.,  8.,  1.,  2.,  8.,  6.,
        1.,  5.,  2.,  1.,  1., 12.,  5.,  1.,  1.,  6.,  6.,  2.,  9.,
        2.,  6.,  2.,  2.,  4.,  1.,  4.,  1.,  6.,  9.,  6.,  8.,  2.,
        9.,  7., 10.,  3.,  3.,  8.,  4.,  2.,  9.,  2.,  1.,  1.,  2.,
        1.,  6.,  3.,  1.,  1.,  1., 11.,  1.,  1.])

In [194]:
max_length_ans = np.max(len_answers)
max_length_ans

19.0

In [195]:
ans_mean = np.mean(len_answers)
ans_std = np.std(len_answers)
print(ans_mean)
print(ans_std)

4.4523809523809526
3.730200945387597


In [196]:
final_dict["Len(A)"] = f"{ans_mean:0.2f} +- {ans_std:0.2f}"
final_dict["Max(A)"] = max_length_ans
final_dict["Len(A)"]

'4.45 +- 3.73'

#### Length of distractors

In [197]:
len_distractors = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "Distractor":
            dist = choice["text"]
            len_distractors.append(count_words(dist))

len_distractors = np.array(len_distractors)
len_distractors

array([ 4,  1, 10,  5,  2,  2,  5,  8,  1,  1, 29, 14,  6,  3,  5,  1,  3,
        2,  1,  1,  3,  3,  6,  9,  1,  1,  2,  3,  3,  7,  5,  7,  1,  5,
        1,  1,  1,  1,  7,  1,  3,  2,  9,  7, 13,  9,  1,  1,  1,  1,  2,
        1,  1,  3, 11,  9,  2,  1,  2, 13,  6,  3, 10, 16,  1,  6,  4,  6,
        1,  1,  1,  2,  3,  1,  1,  1,  2,  3,  1,  1,  1,  1,  3,  7,  5,
        3,  3,  1,  6,  4,  2,  2,  1,  4,  4,  1,  3, 10,  4,  4,  1,  1,
        1,  1,  4,  6,  1,  2, 11,  5,  4, 14,  8,  8,  1,  3,  1,  1,  6,
       13,  1,  3,  6,  5,  5,  3,  1,  6,  8,  4,  2,  1,  5,  3,  8,  8,
        2,  3,  5,  2,  7,  6,  9,  6,  8, 10,  8, 20,  1,  1,  4,  1,  7,
       17,  9, 16, 15, 13,  2,  1,  5,  6,  3,  8,  1,  1,  1,  1,  9, 11,
        8,  5,  2,  1,  1,  1, 11, 11,  7,  6,  2,  2,  3,  7,  1,  3,  2,
        4,  2,  2,  1,  1,  1,  1,  1,  1,  5,  6,  3,  1,  4,  4,  7,  3,
       11,  6,  7,  6,  2,  1,  4,  9,  8,  3,  6,  8,  4,  4,  1,  1,  1,
        3,  1,  5,  6,  3

In [198]:
max_length_dist = np.max(len_distractors)
max_length_dist

29

In [199]:
dist_mean = np.mean(len_distractors)
dist_std = np.std(len_distractors)
print(dist_mean)
print(dist_std)

4.085820895522388
3.9242007073800624


In [200]:
final_dict["Len(D)"] = f"{dist_mean:0.2f} +- {dist_std:0.2f}"
final_dict["Max(D)"] = max_length_dist
final_dict["Len(D)"]

'4.09 +- 3.92'

### Diference ans and Dist

In [201]:
len_differences = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    dists_length = []
    for choice in choices:
        if choice["type"] == "Correct answer":
            ans = choice["text"]
            ans_length = count_words(ans)
        if choice["type"] == "Distractor":
            dist = choice["text"]
            dists_length.append(count_words(dist))
    
    arr_diff = np.array([abs(ans_length-x) for x in dists_length])
    diff = np.mean(arr_diff)
    len_differences.append(diff)

len_differences = np.array(len_differences)
len_differences

array([ 1.5       ,  2.5       ,  1.        ,  2.5       ,  0.        ,
        7.5       ,  2.5       ,  2.        ,  1.5       ,  1.        ,
        6.        ,  1.5       ,  3.        ,  1.5       ,  3.        ,
        9.        ,  2.        ,  0.        ,  0.        ,  3.        ,
        0.5       ,  3.        ,  3.        ,  0.        ,  0.        ,
        1.5       ,  1.        ,  2.        ,  0.5       ,  5.5       ,
        3.5       ,  3.        ,  2.5       ,  5.        ,  0.        ,
        1.5       ,  2.        ,  1.        ,  2.5       ,  0.        ,
        0.        ,  3.        ,  4.        ,  1.        ,  1.        ,
        1.        ,  1.5       ,  1.5       ,  3.5       ,  1.        ,
        0.        ,  0.        ,  3.        ,  0.5       ,  5.        ,
        5.        ,  1.        ,  1.        ,  0.        ,  3.5       ,
        1.        ,  2.5       ,  1.        ,  2.5       ,  2.        ,
        1.5       ,  1.        ,  2.        ,  0.5       ,  2.5 

In [202]:
max_length_diff = np.max(len_differences)
max_length_diff

10.0

In [203]:
diff_mean = np.mean(len_differences)
diff_std = np.std(len_differences)
print(diff_mean)
print(diff_std)

2.036375661375662
1.9892373561823293


In [204]:
final_dict["|Len(A) - Len(D)|"] = f"{diff_mean:0.2f} +- {diff_std:0.2f}"
final_dict["Max(|Len(A) - Len(D)|)"] = max_length_diff
final_dict["|Len(A) - Len(D)|"]

'2.04 +- 1.99'

# Final CSV

In [205]:
df = pd.Series(final_dict, name=data_name)
df

# of texts                              64
# of MCQs                              126
# of D                        2.13 +- 0.38
Len(Text)                 352.10 +- 232.41
Max(Text)                           2140.0
Len(A)                        4.45 +- 3.73
Max(A)                                19.0
Len(D)                        4.09 +- 3.92
Max(D)                                  29
|Len(A) - Len(D)|             2.04 +- 1.99
Max(|Len(A) - Len(D)|)                10.0
Name: dev, dtype: object

In [206]:
df.to_csv(file_output)