In [137]:
import numpy as np
import pandas as pd
import json

In [138]:
# file_name = "training.json"
# file_output = "training_stats.csv"
# data_name = "training"

In [139]:
file_name = "dev.json"
file_output = "dev_stats.csv"
data_name = "dev"

In [140]:
# file_name = "test.json"
# file_output = "test_stats.csv"
# data_name = "test"

In [141]:
f = open(file_name)
data = json.load(f)
f.close()

In [142]:
arr = data['data']
N = len(arr)

In [143]:
final_dict = {}

#### NUmber of texts

In [144]:
text_set = set()
for element in arr:
    text_set.add(element["context"])

n_texts = len(text_set)
final_dict["# of texts"] = n_texts
n_texts

434

#### Count Questions

In [145]:
n_questions = len(arr)
final_dict["# of MCQs"] = n_questions
n_questions

962

#### One answer per choice

In [146]:
n_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_ans = 0  
    for choice in choices:
        if choice["type"] == "Correct answer":
            n_ans +=1
    n_answers[idx] = n_ans

In [147]:
n_answers

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [148]:
# for element in n_answers:
#     assert element == 1

#### Number of distractors

In [149]:
n_distractors = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    n_dist = 0 
    for choice in choices:
        if choice["type"] == "Distractor":
            n_dist +=1
    # assert n_dist < 5
    n_distractors[idx] = n_dist

In [150]:
n_distractors

array([ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        3.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2

In [151]:
n_dist_mean = np.mean(n_distractors)
n_dist_std = np.std(n_distractors)

In [152]:
print(n_dist_mean)
print(n_dist_std)
final_dict["# of D"] = f"{n_dist_mean:0.2f} +- {n_dist_std:0.2f}"
final_dict["# of D"]

2.1476091476091477
0.5424203679347014


'2.15 +- 0.54'

### Length of texts

In [153]:
def count_words(_string):
    arr = _string.split(" ")
    return len(arr)

In [154]:
len_texts = np.zeros(N)
for idx, element in enumerate(arr):
    context = element["context"]
    len_texts[idx] = count_words(context)

len_texts

array([ 371.,  306.,  321.,  352.,  326.,  372.,  372.,  326.,  202.,
        372.,  236.,  311.,  402.,  298.,  369.,  310.,  203.,  409.,
        409.,  216.,  309.,  368.,  122.,  347.,  339.,  312.,  339.,
        249.,  368.,  326.,  315.,  409.,  318.,  302.,  248.,  328.,
        244.,  288.,  323.,  125.,  228.,  370.,  340.,  314.,  390.,
        331.,  246.,  298.,  228.,  223.,  271.,  362.,  368.,  311.,
        344.,  231.,  247.,  368.,  310.,  219.,  207.,  389.,  265.,
        279.,  338.,  228.,  360.,  373.,  223.,  370.,  375.,  414.,
        244.,  325.,  325.,  266.,  266.,  223.,  294.,  294.,  260.,
        260.,  334.,  226.,  226.,  201.,  250.,  236.,  253.,  253.,
        198.,  238.,  238.,  243.,  287.,  287.,  223.,  264.,  264.,
        303.,  565.,  565.,  301.,  230.,  309.,  309.,  257.,  257.,
        217.,  217.,  217.,  248.,  297.,  297.,  362.,  403.,  273.,
        314.,  314.,  314.,  314.,  253.,  253.,  288.,  288.,  256.,
        256.,  373.,

In [155]:
max_length_text = np.max(len_texts)
max_length_text

2142.0

In [156]:
text_mean = np.mean(len_texts)
text_std = np.std(len_texts)
print(text_mean)
print(text_std)

380.6923076923077
332.7966341658794


In [157]:
final_dict["Len(Text)"] = f"{text_mean:0.2f} +- {text_std:0.2f}"
final_dict["Max(Text)"] = max_length_text
final_dict["Len(Text)"]

'380.69 +- 332.80'

#### Length of answers

In [158]:
len_answers = np.zeros(N)
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "Correct answer":
            ans = choice["text"]
            len_answers[idx] = count_words(ans)

len_answers

array([11.,  2.,  2.,  2.,  2.,  2.,  9.,  1.,  1.,  6., 10.,  1.,  1.,
        1., 11.,  1.,  5.,  6.,  1.,  6.,  1.,  1.,  5.,  2.,  1.,  1.,
        7.,  6.,  3.,  2.,  8.,  3.,  1.,  4.,  1.,  1.,  2.,  1.,  2.,
        2.,  4.,  4.,  2., 12.,  2.,  2.,  5.,  1., 12.,  6.,  1.,  2.,
        1.,  6., 11.,  2.,  5.,  2.,  2.,  1.,  3.,  1., 12.,  1.,  1.,
       11.,  4.,  6.,  2.,  2.,  5.,  4.,  5.,  1.,  1.,  9.,  2.,  7.,
        1.,  1.,  3.,  6.,  6.,  3.,  6.,  5.,  1.,  1.,  1.,  1.,  2.,
        1.,  6.,  8.,  5.,  1.,  3., 10.,  2.,  2.,  1.,  9.,  6.,  1.,
        2.,  7.,  2.,  2.,  8.,  2.,  1.,  2.,  8.,  3.,  1.,  1.,  4.,
        8.,  7.,  1.,  2.,  8.,  5.,  8.,  1.,  1.,  7.,  3.,  1.,  1.,
        1.,  3.,  1.,  3.,  2.,  4.,  3.,  3.,  1.,  1.,  2.,  8.,  8.,
       12., 10., 14., 11.,  8., 11.,  9.,  6.,  2.,  2.,  3.,  9.,  5.,
        8.,  5.,  2.,  3.,  6.,  5.,  1., 10.,  4.,  2.,  8.,  8.,  1.,
        1.,  6., 10.,  4.,  5.,  9.,  1.,  1., 12.,  1.,  1.,  7

In [159]:
max_length_ans = np.max(len_answers)
max_length_ans

23.0

In [160]:
ans_mean = np.mean(len_answers)
ans_std = np.std(len_answers)
print(ans_mean)
print(ans_std)

4.1902286902286905
3.4418526156635845


In [161]:
final_dict["Len(A)"] = f"{ans_mean:0.2f} +- {ans_std:0.2f}"
final_dict["Max(A)"] = max_length_ans
final_dict["Len(A)"]

'4.19 +- 3.44'

#### Length of distractors

In [162]:
len_distractors = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    for choice in choices:
        if choice["type"] == "Distractor":
            dist = choice["text"]
            len_distractors.append(count_words(dist))

len_distractors = np.array(len_distractors)
len_distractors

array([8, 4, 2, ..., 5, 9, 3])

In [163]:
max_length_dist = np.max(len_distractors)
max_length_dist

24

In [164]:
dist_mean = np.mean(len_distractors)
dist_std = np.std(len_distractors)
print(dist_mean)
print(dist_std)

4.3233301064859635
3.835813271076297


In [165]:
final_dict["Len(D)"] = f"{dist_mean:0.2f} +- {dist_std:0.2f}"
final_dict["Max(D)"] = max_length_dist
final_dict["Len(D)"]

'4.32 +- 3.84'

### Diference ans and Dist

In [166]:
len_differences = []
for idx, element in enumerate(arr):
    choices = element["choices"]
    dists_length = []
    for choice in choices:
        if choice["type"] == "Correct answer":
            ans = choice["text"]
            ans_length = count_words(ans)
        if choice["type"] == "Distractor":
            dist = choice["text"]
            dists_length.append(count_words(dist))
    
    arr_diff = np.array([abs(ans_length-x) for x in dists_length])
    diff = np.mean(arr_diff)
    len_differences.append(diff)

len_differences = np.array(len_differences)
len_differences

array([ 5.        ,  0.5       ,  0.        ,  1.        ,  0.5       ,
        2.5       ,  1.        ,  0.        ,  1.        ,  5.        ,
        4.5       ,  0.        ,  7.        ,  3.5       ,  7.        ,
        0.        ,  2.5       ,  3.        ,  0.        ,  1.5       ,
        2.5       ,  0.        ,  4.        ,  1.        ,  1.        ,
        1.        ,  0.5       ,  5.        ,  1.        ,  1.        ,
        3.5       ,  1.5       ,  2.        ,  2.5       ,  0.        ,
        0.        ,  0.5       ,  3.        ,  0.5       ,  0.5       ,
        1.        ,  6.5       ,  0.        ,  3.5       ,  0.        ,
        3.5       ,  5.        ,  0.        ,  5.5       ,  3.5       ,
        0.5       ,  0.5       ,  0.        ,  5.        ,  1.        ,
        0.5       ,  1.        ,  0.5       ,  1.5       ,  0.        ,
        4.        ,  0.        ,  5.5       ,  0.        ,  0.        ,
        1.5       ,  1.        ,  1.5       ,  1.5       ,  1.5 

In [167]:
max_length_diff = np.max(len_differences)
max_length_diff

13.5

In [168]:
diff_mean = np.mean(len_differences)
diff_std = np.std(len_differences)
print(diff_mean)
print(diff_std)

2.061174636174636
2.1248184560650607


In [169]:
final_dict["|Len(A) - Len(D)|"] = f"{diff_mean:0.2f} +- {diff_std:0.2f}"
final_dict["Max(|Len(A) - Len(D)|)"] = max_length_diff
final_dict["|Len(A) - Len(D)|"]

'2.06 +- 2.12'

# Final CSV

In [170]:
df = pd.Series(final_dict, name=data_name)
df

# of texts                             434
# of MCQs                              962
# of D                        2.15 +- 0.54
Len(Text)                 380.69 +- 332.80
Max(Text)                           2142.0
Len(A)                        4.19 +- 3.44
Max(A)                                23.0
Len(D)                        4.32 +- 3.84
Max(D)                                  24
|Len(A) - Len(D)|             2.06 +- 2.12
Max(|Len(A) - Len(D)|)                13.5
Name: training, dtype: object

In [171]:
df.to_csv(file_output)